name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    env:
      BUILD_CONFIGURATION: Mon
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --configuration ${{ env.BUILD_CONFIGURATION }} --output .output -r win-x64
    - name: Copy script files
      run: |
        cp scripts/* .output
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        path: .output/**/*
        if-no-files-found: error
